 /*   04 February 2006 19:01:07   User:    Server: (LOCAL)   Database: lb_staging   Application: MS SQLEM - Data Tools*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.apollo_users ADD
	ReceiveNewsletter bit NOT NULL CONSTRAINT DF_apollo_users_ReceiveNewsletter DEFAULT 1
GO
COMMIT