/*CREATE NONCLUSTERED INDEX [_dta_index_InstantForum_Topics_5_1720393198__K4_K16]
    ON [dbo].[InstantForum_Topics]([ParentID] ASC, [Queued] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];*/

