/*CREATE CLUSTERED INDEX [_dta_index_InstantForum_TopicsRead_c_5_20911146__K3_K2]
    ON [dbo].[InstantForum_TopicsRead]([ReadUserID] ASC, [ReadTopicID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0);*/

