CREATE NONCLUSTERED INDEX [IDX_Secondary]
    ON [dbo].[apollo_gallery_categories]([ParentSiteID] ASC, [f_name] ASC, [f_type] ASC, [f_active] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

