/*CREATE NONCLUSTERED INDEX [IX_InstantForum_ForumsRoles_RoleID]
    ON [dbo].[InstantForum_ForumsRoles]([RoleID] ASC) WITH (FILLFACTOR = 30, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];*/

