ALTER TABLE [dbo].[apollo_content_images]
    ADD CONSTRAINT [PK_apollo_content_images] PRIMARY KEY CLUSTERED ([ContentID] ASC, [ImageID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

