ALTER TABLE [dbo].[apollo_roles]
    ADD CONSTRAINT [PK_apollo_roles] PRIMARY KEY CLUSTERED ([f_key] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

