ALTER TABLE [dbo].[apollo_related_objects]
    ADD CONSTRAINT [PK_apollo_related_objects_1] PRIMARY KEY CLUSTERED ([ObjectAID] ASC, [ObjectBID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

