ALTER TABLE [dbo].[apollo_rights]
    ADD CONSTRAINT [PK_apollo_rights] PRIMARY KEY CLUSTERED ([f_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

