ALTER TABLE [dbo].[apollo_users]
    ADD CONSTRAINT [PK_apollo_users] PRIMARY KEY CLUSTERED ([f_uid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

