ALTER TABLE [dbo].[apollo_site_languages]
    ADD CONSTRAINT [PK_apollo_site_languages] PRIMARY KEY CLUSTERED ([LanguageID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

