ALTER TABLE [dbo].[BlacklistedReferrers]
    ADD CONSTRAINT [PK_BlacklistedReferrers] PRIMARY KEY CLUSTERED ([Url] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

