ALTER TABLE [dbo].[DirectoryCategoryItems]
    ADD CONSTRAINT [PK_DirectoryCategoryItems_1] PRIMARY KEY CLUSTERED ([CategoryID] ASC, [ItemID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

