ALTER TABLE [dbo].[dtproperties]
    ADD CONSTRAINT [pk_dtproperties] PRIMARY KEY CLUSTERED ([id] ASC, [property] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

