/*ALTER TABLE [dbo].[InstantASP_Emails]
    ADD CONSTRAINT [PK_InstantASP_EmailQueue_EmailID] PRIMARY KEY CLUSTERED ([EmailID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

