/*ALTER TABLE [dbo].[InstantForum_IFCode]
    ADD CONSTRAINT [PK_InstantForum_IFCode_IFCodeID] PRIMARY KEY CLUSTERED ([IFCodeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

