/*ALTER TABLE [dbo].[InstantForum_ForumsModerators]
    ADD CONSTRAINT [PK_InstantForum_ForumsModerators_ForumModeratorID] PRIMARY KEY CLUSTERED ([ForumModeratorID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

