/*ALTER TABLE [dbo].[InstantForum_Settings]
    ADD CONSTRAINT [PK_InstantForum_Settings_SettingID] PRIMARY KEY CLUSTERED ([SettingID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

