/*ALTER TABLE [dbo].[InstantForum_Moderators]
    ADD CONSTRAINT [PK_InstantForum_Moderators] PRIMARY KEY CLUSTERED ([ModeratorForumID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

