/*ALTER TABLE [dbo].[InstantForum_Forums]
    ADD CONSTRAINT [PK_InstantForum_Forums] PRIMARY KEY CLUSTERED ([ForumID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

