/*ALTER TABLE [dbo].[InstantForum_SearchResults]
    ADD CONSTRAINT [PK_InstantForum_SearchResults_ResultID] PRIMARY KEY CLUSTERED ([ResultID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

