/*ALTER TABLE [dbo].[InstantASP_Users]
    ADD CONSTRAINT [PK_InstantASP_Users_UserID] PRIMARY KEY CLUSTERED ([UserID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

