/*ALTER TABLE [dbo].[InstantASP_ScheduledTasks]
    ADD CONSTRAINT [PK_InstantForum_ScheduledTasks_TaskID] PRIMARY KEY CLUSTERED ([TaskID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

