/*ALTER TABLE [dbo].[InstantForum_ForumsRead]
    ADD CONSTRAINT [PK_InstantForum_ForumsRead_ForumsReadID] PRIMARY KEY CLUSTERED ([ForumsReadID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

