/*ALTER TABLE [dbo].[InstantForum_EventsRoles]
    ADD CONSTRAINT [PK_InstantForum_EventsRoles_EventRoleID] PRIMARY KEY CLUSTERED ([EventRoleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

