/*ALTER TABLE [dbo].[InstantForum_WhosOn]
    ADD CONSTRAINT [PK_InstantForum_WhosOn_WhosOnID] PRIMARY KEY CLUSTERED ([WhosOnID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

