/*ALTER TABLE [dbo].[InstantASP_Sessions]
    ADD CONSTRAINT [PK_InstantASP_Sessions_SessionID] PRIMARY KEY CLUSTERED ([SessionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

