/*ALTER TABLE [dbo].[InstantForum_Topics]
    ADD CONSTRAINT [PK_InstantForum_Topics_PostID] PRIMARY KEY CLUSTERED ([PostID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

