/*ALTER TABLE [dbo].[InstantASP_Roles]
    ADD CONSTRAINT [PK_InstantASP_Roles_RoleID_RoleID] PRIMARY KEY CLUSTERED ([RoleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

