/*ALTER TABLE [dbo].[InstantForum_ForumSubscriptions]
    ADD CONSTRAINT [PK_InstantForum_ForumSubscriptions] PRIMARY KEY CLUSTERED ([ForumSubscriptionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

