/*ALTER TABLE [dbo].[InstantForum_PollAnswers]
    ADD CONSTRAINT [PK_InstantForum_PollAnswers_PollAnswerID] PRIMARY KEY CLUSTERED ([PollAnswerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

