/*ALTER TABLE [dbo].[InstantForum_Polls]
    ADD CONSTRAINT [PK_InstantForum_Polls_PollID] PRIMARY KEY CLUSTERED ([PollID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

