/*ALTER TABLE [dbo].[InstantForum_Attachments]
    ADD CONSTRAINT [PK_InstantForum_Attachments_AttachmentID] PRIMARY KEY CLUSTERED ([AttachmentID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

