/*ALTER TABLE [dbo].[InstantForum_LanguageFilters]
    ADD CONSTRAINT [PK_InstantForum_LanguageFilters_LanguageFilterID] PRIMARY KEY CLUSTERED ([LanguageFilterID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

