/*CREATE TABLE [dbo].[InstantASP_Users] (
    [UserID]                    INT            IDENTITY (1, 1) NOT NULL,
    [EmailAddress]              NVARCHAR (255) DEFAULT ('') NOT NULL,
    [Password]                  NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [Username]                  NVARCHAR (255) DEFAULT (N'') NOT NULL,
    [PrimaryRoleID]             SMALLINT       DEFAULT ((1)) NOT NULL,
    [Culture]                   NVARCHAR (20)  DEFAULT (N'en-us') NOT NULL,
    [IPAddress]                 NVARCHAR (20)  DEFAULT (N'') NOT NULL,
    [TimeZoneOffset]            FLOAT          DEFAULT ((0)) NOT NULL,
    [ObserveDaylightSavingTime] BIT            DEFAULT ((0)) NOT NULL,
    [DateTimeFormat]            NVARCHAR (1)   DEFAULT ('g') NOT NULL,
    [TotalVisits]               INT            DEFAULT ((1)) NOT NULL,
    [CreatedDate]               DATETIME       DEFAULT (getdate()) NOT NULL,
    [LastLoginDate]             DATETIME       DEFAULT (getdate()) NOT NULL,
    [ConfirmationCode]          NVARCHAR (25)  DEFAULT ('') NOT NULL,
    [FirstDayOfWeek]            TINYINT        DEFAULT ((0)) NOT NULL,
    [FirstName]                 NVARCHAR (155) DEFAULT ('') NOT NULL,
    [LastName]                  NVARCHAR (155) DEFAULT ('') NOT NULL,
    [CompanyName]               NVARCHAR (255) DEFAULT ('') NOT NULL,
    [JobTitle]                  NVARCHAR (255) DEFAULT ('') NOT NULL,
    [PublicEmail]               NVARCHAR (255) DEFAULT ('') NOT NULL,
    [WebAddress]                NVARCHAR (255) DEFAULT ('') NOT NULL,
    [BlogAddress]               NVARCHAR (255) DEFAULT ('') NOT NULL,
    [OpenID]                    NVARCHAR (255) DEFAULT ('') NOT NULL,
    [PhotoImage]                NVARCHAR (255) DEFAULT ('') NOT NULL,
    [MSN]                       NVARCHAR (155) DEFAULT ('') NOT NULL,
    [Skype]                     NVARCHAR (155) DEFAULT ('') NOT NULL,
    [YIM]                       NVARCHAR (155) DEFAULT ('') NOT NULL,
    [AIM]                       NVARCHAR (155) DEFAULT ('') NOT NULL,
    [ICQ]                       NVARCHAR (155) DEFAULT ('') NOT NULL,
    [Twitter]                   NVARCHAR (100) DEFAULT ('') NOT NULL,
    [Facebook]                  NVARCHAR (100) DEFAULT ('') NOT NULL,
    [LinkedIn]                  NVARCHAR (100) DEFAULT ('') NOT NULL,
    [MySpace]                   NVARCHAR (100) DEFAULT ('') NOT NULL,
    [YouTube]                   NVARCHAR (100) DEFAULT ('') NOT NULL,
    [Location]                  NVARCHAR (100) DEFAULT ('') NOT NULL,
    [DOBDay]                    TINYINT        DEFAULT ((0)) NOT NULL,
    [DOBMonth]                  TINYINT        DEFAULT ((0)) NOT NULL,
    [DOBYear]                   INT            DEFAULT ((0)) NOT NULL,
    [UserLevelTitle]            NVARCHAR (100) DEFAULT ('') NOT NULL,
    [UserLevelImageURL]         NVARCHAR (100) DEFAULT ('') NOT NULL,
    [LdapUsername]              NVARCHAR (100) DEFAULT ('') NOT NULL,
    [UsernameEncoded]           NVARCHAR (155) DEFAULT ('') NOT NULL
);*/



