 SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PopularTags](
	[SectionID] [tinyint] NOT NULL,
	[Tag] [nvarchar](256) NOT NULL,
	[Occurrences] [int] NOT NULL CONSTRAINT [DF_PopularTags_Occurrences]  DEFAULT ((1)),
 CONSTRAINT [PK_PopularTags] PRIMARY KEY CLUSTERED 
(
	[SectionID] ASC,
	[Tag] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]